now = new Date();
localtime = now.toString();
utctime = now.toGMTString();
document.write("<b>Local time:</b>"+localtime+"<br>");
document.write("<b>UTC time:</b>"+utctime+"<br>");
hours = now.getHours();
mins = now.getMinutes();
secs = now.getSeconds();
document.write("<h3>");
document.write(hours+":"+mins+":"+secs);
document.write("</h3>");
alert(document.title);