now = new Date();
localtime = now.toString();
utctime = now.toGMTString();
document.write("<b>Local time:</b>"+localtime+"<br>");
document.write("<b>UTC time:</b>"+utctime+"<br>");
hours = now.getHours();
mins = now.getMinutes();
secs = now.getSeconds();
document.write("<h3>");
document.write(hours+":"+mins+":"+secs);
document.write("</h3>");
millsecs = now.getMilliseconds();
document.write("<p>");
document.write("<b>Milliseconds 1:</b><br>");
document.write(millsecs+"<br>");
document.write("<\p>");
millsecs = now.getMilliseconds();
document.write("<p>");
document.write("<b>Milliseconds 2:</b><br>");
document.write(millsecs+"<br>");
document.write("<\p>");
millsecs = now.getMilliseconds();
document.write("<p>");
document.write("<b>Milliseconds 3:</b><br>");
document.write(millsecs+"<br>");
document.write("<\p>");